### PR TITLE
Simplify sourcePath string

### PR DESCRIPTION
**Pull request by Wiejeben**
I personally couldn't get it to work with the @ symbol and to me this is just another thing I don't have to change when changing folder names.

### CODE REVIEW

**Comment by khalwat** [comment]
Strange you couldn't get it to work with Yii aliases. What was going wrong?

**Comment by Wiejeben** [comment]
I'm actually not sure. I tried to use `@oberonamsterdam/craft-manytomany/assetbundles/manytomanyfield/dist` on [this file](https://github.com/oberonamsterdam/craft-manytomany/blob/master/src/assetbundles/manytomanyfield/ManyToManyFieldAsset.php), but whatever I tried, it always resulted in an "Invalid path alias" error.

**Comment by khalwat** [comment]
What is the actual plugin handle of your plugin @Wiejeben ?

**Comment by Wiejeben** [comment]
It's craft-manytomany, as configured in the [composer.json](https://github.com/oberonamsterdam/craft-manytomany/blob/master/composer.json#L39).

**Pull request closed without merging**
